name: bootstrap_modal
description: Creating modals with ng_bootstrap
version: 0.0.1-rc1
#homepage: https://www.example.com
#author: iblasco <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular: ^4.0.0-alpha+2
  angular_components: 0.6.0-alpha+2

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
